2025-06-26 12:00:03.426671: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Training Net 10:   0%|          | 0/30000000 [00:00<?, ?it/s]/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([30, 1, 1])) that is different to the input size (torch.Size([30, 1, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([200, 1, 1])) that is different to the input size (torch.Size([200, 1, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Training Net 10:   0%|          | 0/30000000 [00:00<?, ?it/s, loss=285.9272, epoch:0]Exception in thread Thread-987:
Training Net 10:   0%|          | 1000/30000000 [00:01<8:39:08, 963.11it/s, loss=285.9272, epoch:0]Traceback (most recent call last):

  File "/home/akiva/FCNX-Ensembling/FCN3Exps/net_einsum_parallel.py", line 585, in train_net
  File "/home/akiva/FCNX-Ensembling/FCN3Exps/net_einsum_parallel.py", line 251, in epoch_callback_fcn3
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/torch/utils/tensorboard/writer.py", line 421, in add_scalars
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/torch/utils/tensorboard/writer.py", line 76, in __init__
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/event_file_writer.py", line 100, in __init__
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/event_file_writer.py", line 125, in flush
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/event_file_writer.py", line 194, in flush
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/event_file_writer.py", line 212, in _check_worker_status
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/event_file_writer.py", line 244, in run
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/event_file_writer.py", line 275, in _run
    self._record_writer.write(data)
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorflow/python/lib/io/file_io.py", line 100, in write
    self._prewrite_check()
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _prewrite_check
    self._writable_file = _pywrap_file_io.WritableFile(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.ResourceExhaustedError: /home/akiva/gpnettrain/fcn3_FL_run_20250626_120001_epochs_30000000/epochs_30000000_N:1000_chi_1000_D:3_P:30_k:1.0_ondata_True_10/FCN2_epochs_30000000_N:1000_chi_1000_D:3_P:30_k:1.0_ondata_True_10_lambda_H(W1)_984/events.out.tfevents.1750928405.zohar-gpu-2.174736.985; Too many open files
Traceback (most recent call last):
  File "/home/akiva/FCNX-Ensembling/FCN3Exps/net_einsum_parallel.py", line 602, in <module>
    net.train_net() # k=0 since we are running one net at a time
    ^^^^^^^^^^^^^^^
  File "/home/akiva/FCNX-Ensembling/FCN3Exps/net_einsum_parallel.py", line 585, in train_net
    epoch_callback_fcn3(epoch, loss, writer, self.net, self.inputs.squeeze(1), ens)
  File "/home/akiva/FCNX-Ensembling/FCN3Exps/net_einsum_parallel.py", line 251, in epoch_callback_fcn3
    writer.add_scalars(f'FCN2_{TRAINID}/lambda_H(W1)', scalarsH, epoch)
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/torch/utils/tensorboard/writer.py", line 421, in add_scalars
    fw = FileWriter(
         ^^^^^^^^^^^
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/torch/utils/tensorboard/writer.py", line 76, in __init__
    self.event_writer = EventFileWriter(
                        ^^^^^^^^^^^^^^^^
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/event_file_writer.py", line 100, in __init__
    self.flush()
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/event_file_writer.py", line 125, in flush
    self._async_writer.flush()
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/event_file_writer.py", line 194, in flush
    self._check_worker_status()
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/event_file_writer.py", line 212, in _check_worker_status
    raise exception
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/event_file_writer.py", line 244, in run
    self._run()
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/event_file_writer.py", line 275, in _run
    self._record_writer.write(data)
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorflow/python/lib/io/file_io.py", line 100, in write
    self._prewrite_check()
  File "/home/akiva/miniconda3/envs/ml_env/lib/python3.11/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _prewrite_check
    self._writable_file = _pywrap_file_io.WritableFile(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.ResourceExhaustedError: /home/akiva/gpnettrain/fcn3_FL_run_20250626_120001_epochs_30000000/epochs_30000000_N:1000_chi_1000_D:3_P:30_k:1.0_ondata_True_10/FCN2_epochs_30000000_N:1000_chi_1000_D:3_P:30_k:1.0_ondata_True_10_lambda_H(W1)_984/events.out.tfevents.1750928405.zohar-gpu-2.174736.985; Too many open files
